dist: trusty
sudo: required
language: java
install: true
services:
  - postgresql
script:
  - cd bi/postgres
  - mvn test -B
notifications:
  slack: ldbcouncil:JRXP43nDV4KRgtclmoNZJpyq
  email: false
  on_success: change
  on_failure: always
