dist: trusty
sudo: required
language: java
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - git clone --depth=1 https://github.com/ldbc/ldbc_snb_driver
  - cd ldbc_snb_driver
  - mvn install -DskipTests
  - cd ..
script:
  - cd bi/postgres
  - mvn test -B
notifications:
  slack: ldbcouncil:JRXP43nDV4KRgtclmoNZJpyq
  email: false
  on_success: change
  on_failure: always
